apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyI0NGNlNzg5Yi1rcjEtcmVnaXN0cnkuY29udGFpbmVyLm5obmNsb3VkLmNvbS9jb250YWluZXItcGxhdGZvcm0tcmVnaXN0cnkiOnsidXNlcm5hbWUiOiJYQ0ExT2owRnFBOE9NaGFsT1VoSyIsInBhc3N3b3JkIjoiekdneG83WGxwazVvalk3diIsImF1dGgiOiJXRU5CTVU5cU1FWnhRVGhQVFdoaGJFOVZhRXM2ZWtkbmVHODNXR3h3YXpWdmFsazNkZz09In19fQ==
kind: Secret
metadata:
  annotations:
    strategy.spinnaker.io/versioned: "false"
  name: ncr
type: kubernetes.io/dockerconfigjson

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-front
  labels:
    app: test-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-front
  template:
    metadata:
      labels:
        app: test-front
    spec:
      containers:
      - name: test-front
        image: 44ce789b-kr1-registry.container.nhncloud.com/container-platform-registry/test-front:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: test-front
spec:
  type: NodePort
  selector:
    app: test-front
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30092
      protocol: TCP
